import { createLegacyFontConverter } from './legacyFont.js';

// Himali's (FONTASY_HIMALI_TT) key-to-glyph mapping is font-designer-
// arbitrary (not phonetic), so this table is cross-checked against two
// independent open-source converters rather than taken from one source:
//  - casualsnek/npttf2utf (src/npttf2utf/map.json, key "FONTASY_HIMALI_TT")
//    https://github.com/casualsnek/npttf2utf
//  - sapradhan/nep-ttf2utf (rules/fontasy_himali_tt.yaml)
//    https://github.com/sapradhan/nep-ttf2utf
// 122 of 124 keys matched exactly between the two; the only disagreement
// was on '¥' (a key already found unreliable for the same reason in
// Preeti's own table — this converter never uses '¥' for anything, so the
// disagreement doesn't affect us). Post-rules in both sources are
// byte-for-byte identical to Preeti's, confirming this font shares the
// same reph/subscript-र/compound-matra conventions createLegacyFontConverter
// already implements.
export const HIMALI_TO_UNICODE: Record<string, string> = {
  '~': 'ञ',
  '!': 'ज्ञ',
  '@': 'द्द',
  '#': 'घ',
  $: 'द्ध',
  '%': 'छ',
  '^': 'ट',
  '&': 'ठ',
  '*': 'ड',
  '(': 'ढ',
  ')': 'ण्',
  _: ')',
  '+': 'ं',
  '`': 'ञ्',
  '1': '१',
  '2': '२',
  '3': '३',
  '4': '४',
  '5': '५',
  '6': '६',
  '7': '७',
  '8': '८',
  '9': '९',
  '0': '०',
  '-': '(',
  '=': '.',
  Q: 'त्त',
  W: 'ध्',
  E: 'भ्',
  R: 'च्',
  T: 'त्',
  Y: 'थ्',
  U: 'ग्',
  I: 'क्ष्',
  O: 'इ',
  P: 'ए',
  '}': 'ै',
  '|': '्र',
  q: 'त्र',
  w: 'ध',
  e: 'भ',
  r: 'च',
  t: 'त',
  y: 'थ',
  u: 'ग',
  i: 'ष्',
  o: 'य',
  p: 'उ',
  '[': 'ृ',
  ']': 'े',
  '\\': '्',
  A: 'ब्',
  S: 'क्',
  D: 'म्',
  F: 'ा',
  G: 'न्',
  H: 'ज्',
  J: 'व्',
  K: 'प्',
  L: 'ी',
  ':': 'स्',
  '"': 'ू',
  a: 'ब',
  s: 'क',
  d: 'म',
  f: 'ा',
  g: 'न',
  h: 'ज',
  j: 'व',
  k: 'प',
  l: 'ि',
  ';': 'स',
  "'": 'ु',
  Z: 'श्',
  X: 'हृ',
  C: 'ऋ',
  V: 'ख्',
  B: 'द्य',
  N: 'ल्',
  M: 'ः',
  '<': '?',
  '>': 'श्र',
  '?': 'रु',
  z: 'श',
  x: 'ह',
  c: 'अ',
  v: 'ख',
  b: 'द',
  n: 'ल',
  ',': ',',
  '.': '।',
  '/': 'र',
  '¡': 'ज्ञ्',
  '¢': 'द्घ',
  '£': 'घ्',
  '¤': 'ँ',
  '¥': 'र्‍',
  '§': 'ट्ट',
  ª: 'ङ',
  '«': '्र',
  '­': '(',
  '®': '+',
  '°': 'ङ्क',
  '´': 'झ',
  '¶': 'ठ्ठ',
  '¿': 'रू',
  '»': '',
  Æ: '”',
  Ñ: 'ङ',
  Ò: 'ू',
  Ô: 'क्ष',
  '×': '×',
  Ø: '्य',
  Ù: 'ह',
  Ú: 'ु',
  ß: 'द्म',
  å: 'द्व',
  æ: '“',
  ç: 'ॐ',
  é: 'ङ्ग',
  í: 'ष',
  '÷': '/',
  ø: 'य्',
  ú: 'ू',
};

export const { reverseMap: UNICODE_TO_HIMALI, toLegacy: unicodeToHimali } =
  createLegacyFontConverter(HIMALI_TO_UNICODE);
